version: "3"

tasks:
  default:
    cmds:
      - task: readme
  readme:
    cmds:
      - less README.md
  init:
    cmds:
      - >-
        nix run ./#homeConfigurations.{{.USER}}@{{.HOST}}.activationPackage
        --extra-experimental-features nix-command --extra-experimental-features flakes
    vars:
      HOST:
        sh: hostname
  run:
    cmds:
      - nix run ./#homeConfigurations.{{.USER}}@{{.HOST}}.activationPackage
    vars:
      HOST:
        sh: hostname
